(defun gather-users-uid-gid ()
  (let ((uid-lists '())
	(gid-lists '())
	(un (uiop:process-info-output (uiop:launch-program "awk -F: '{print $1}' /etc/passwd" :output :stream)))
	(ui (uiop:process-info-output (uiop:launch-program "awk -F: '{print $3}' /etc/passwd" :output :stream)))
	(gi (uiop:process-info-output (uiop:launch-program "awk -F: '{print $4}' /etc/passwd" :output :stream))))
    (do ((n (read-line un nil)
	    (read-line un nil))
	 (u (read-line ui nil)
	    (read-line ui nil))
	 (g (read-line gi nil)
	    (read-line gi nil)))
	((or (null n) (null u) (null g)))
      (setf uid-lists (append uid-lists (list (cons u n))))
      (setf gid-lists (append gid-lists (list (cons g n)))))
    (values uid-lists gid-lists)))
