#!/usr/local/bin/newlisp

(set 'pwd (append (real-path) "/"))

(define (gather_rmsd file-prefix ) 
  (dolist (i (directory "./" {^[^.]}))
    (begin 
      (if (not (directory? i)) (begin 
				 (let (iffind (starts-with  i file-prefix ))
				   (if iffind (begin
						;(make-dir new-dirname)
						(set 'refer-id (exec (string  "grep FF " i " | awk '{print $1}' " )))
						(set 'compare-id (exec (string  "grep FF " i " | awk '{print $2}'" )))
						(set 'num-mol (exec (string  "grep FF " i " | awk '{print $3}'" )))
						(set 'rmsd (exec (string  "grep FF " i " | awk '{print $7}'" )))
						(set 'xrd (exec (string  "grep FF " i " | awk '{print $8}'" )))
            (set 'n 0)
            ;(println rmsd)
            (set 'rid ((regex {\d{1,3}} (refer-id 0)) 0))
            (dolist (x num-mol)
              (if (> (int x) 4) 
              ;(println (format " %s " rid) (format "%s " ((regex {\d{1,3}} (compare-id n)) 0)) (format "%s " (rmsd n))  (format " %s " (num-mol n)) )
              (println (format " %s " rid) (format "%s " ((regex {\d{1,3}} (compare-id n)) 0)) (format "%s " (rmsd n))  ))
              ;(println (format " %s " rid) (format "%s " ((regex {\d{1,3}} (compare-id n)) 0)) (format "%s " (num-mol n))  ))
              (inc n)
              )
              )
           )
         )
        )
      )
    )
  )
    )

(define (gather_rmsd2 file-prefix ) 

  (dolist (i (directory "./" {^[^.]}))
    (begin 
      (if (not (directory? i)) (begin 
				 (let (iffind (starts-with  i file-prefix ))
				   (if iffind (begin
						;(make-dir new-dirname)
						(set 'refer-id (exec (string  "grep FF " i " | awk '{print $1}' " )))
						(set 'compare-id (exec (string  "grep FF " i " | awk '{print $2}'" )))
						(set 'num-mol (exec (string  "grep FF " i " | awk '{print $3}'" )))
						(set 'rmsd (exec (string  "grep FF " i " | awk '{print $7}'" )))
						(set 'xrd (exec (string  "grep FF " i " | awk '{print $8}'" )))
            (set 'n 0)
            ;(println rmsd)
            (set 'rid ((regex {\d{1,3}} (refer-id 0)) 0))
            (dolist (x num-mol)
              ;(println (format " %s " (refer-id 0)) (format "%s " (compare-id n)) (format " %s " (num-mol n)) (format "%s " (rmsd n)) )
              (println (format " %s " rid) (format "%s " ((regex {\d{1,3}} (compare-id n)) 0))  (format " %s " (num-mol n)) )
              (inc n)
              )
            (println " ")  
            )
           )
         )
        )
      )
    )
  )
    )
;(generate-dftb-jobs "DFTB_st" "unit")
;(generate-dftb-jobs "DFTB_st" "cg")
;(gather_cg_unit "DFTB_st")
;(gather_rmsd2 "crystal_comparison_")
(gather_rmsd "crystal_comparison_")
;(gather_rmsd3)
;(gather_cg_unit "FF_st")
;(gather_cg_unit "DFTB_st")
(exit)
